[pytest]
python_files = test_*.py
testpaths = tests db/gapi/test
addopts = -m "not gdrive_access"
markers =
    gdrive_access: requires access to a Google Drive test spreadsheet
    slow: performs a slow external operation
