[DEFAULT]
; Google Sheets
ADMINS_PAGE_NAME = Admins
USER_DATA_PAGE_NAME = User data
WAR_STAGES_PAGE_NAME = War stages
TEST_GTABLE_KEY = <test spreadsheet id>
TEST_PAGE_NAME = Test

; Google Drive
GSERVICE_EMAIL = <service_account_name@project_name.iam.gserviceaccount.com>
GSERVICE_FILE = gapi_service_file.json

; Logs
LOG_FORMAT = %%(asctime)s: %%(levelname)s: %%(pathname)s::%%(funcName)s::%%(lineno)d: %%(message)s
LOG_DATE_FORMAT = %%d/%%m %%H:%%M:%%S

[Release]
TOKEN = <telegram token>
ADMINS_GTABLE_KEY = <admins spreadsheet id>
GAME_DATA_GTABLE_KEY = <game data spreadsheet id>
GDRIVE_FOLDER_PATH = <google drive folder id>
LOG_FILE_NAME = SalResourcesManager.log

[Test]
TOKEN = <telegram token>
ADMINS_GTABLE_KEY = <admins spreadsheet id>
GAME_DATA_GTABLE_KEY = <game data spreadsheet id>
GDRIVE_FOLDER_PATH = <google drive folder id>
LOG_FILE_NAME = SalResourcesManager.test.log

[Debug]
TOKEN = <telegram token>
ADMINS_GTABLE_KEY = <admins spreadsheet id>
GAME_DATA_GTABLE_KEY = <game data spreadsheet id>
GDRIVE_FOLDER_PATH = <google drive folder id>
LOG_FILE_NAME = SalResourcesManager.debug.log
