CREATE TABLE clan_technologies (
    group_id INTEGER PRIMARY KEY REFERENCES clans(group_id) ON DELETE CASCADE,
    forging_equipment INTEGER NOT NULL DEFAULT 0 CHECK (forging_equipment BETWEEN 0 AND 10),
    summoning_skills INTEGER NOT NULL DEFAULT 0 CHECK (summoning_skills BETWEEN 0 AND 10),
    upgrading_skills INTEGER NOT NULL DEFAULT 0 CHECK (upgrading_skills BETWEEN 0 AND 10),
    tech_tree INTEGER NOT NULL DEFAULT 0 CHECK (tech_tree BETWEEN 0 AND 10),
    forge_upgrades INTEGER NOT NULL DEFAULT 0 CHECK (forge_upgrades BETWEEN 0 AND 10),
    dungeon_keys INTEGER NOT NULL DEFAULT 0 CHECK (dungeon_keys BETWEEN 0 AND 10),
    hatching_eggs INTEGER NOT NULL DEFAULT 0 CHECK (hatching_eggs BETWEEN 0 AND 10),
    merging_pets INTEGER NOT NULL DEFAULT 0 CHECK (merging_pets BETWEEN 0 AND 10),
    summoning_mounts INTEGER NOT NULL DEFAULT 0 CHECK (summoning_mounts BETWEEN 0 AND 10),
    merging_mounts INTEGER NOT NULL DEFAULT 0 CHECK (merging_mounts BETWEEN 0 AND 10),
    clan_war_day_1 INTEGER NOT NULL DEFAULT 0 CHECK (clan_war_day_1 BETWEEN 0 AND 10),
    clan_war_day_2 INTEGER NOT NULL DEFAULT 0 CHECK (clan_war_day_2 BETWEEN 0 AND 10),
    clan_war_day_3 INTEGER NOT NULL DEFAULT 0 CHECK (clan_war_day_3 BETWEEN 0 AND 10),
    clan_war_day_4 INTEGER NOT NULL DEFAULT 0 CHECK (clan_war_day_4 BETWEEN 0 AND 10),
    clan_war_day_5 INTEGER NOT NULL DEFAULT 0 CHECK (clan_war_day_5 BETWEEN 0 AND 10),
    clan_war_day_6 INTEGER NOT NULL DEFAULT 0 CHECK (clan_war_day_6 BETWEEN 0 AND 10),
    clan_war_damage INTEGER NOT NULL DEFAULT 0 CHECK (clan_war_damage BETWEEN 0 AND 100),
    clan_war_health INTEGER NOT NULL DEFAULT 0 CHECK (clan_war_health BETWEEN 0 AND 100),
    personal_rewards INTEGER NOT NULL DEFAULT 0 CHECK (personal_rewards BETWEEN 0 AND 10),
    win_rewards INTEGER NOT NULL DEFAULT 0 CHECK (win_rewards BETWEEN 0 AND 10),
    lose_rewards INTEGER NOT NULL DEFAULT 0 CHECK (lose_rewards BETWEEN 0 AND 10)
);
